apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apic-lab

resources:
# Base resources
- ../../base/management
- ../../base/gateway
- namespace.yaml

# Issuers (necessários para o ManagementCluster)
- selfsigning-issuer.yaml
- ingress-issuer.yaml

# Secrets estáticos (exportados do ambiente)
- secrets-yaml/admin-secret.yaml
- secrets-yaml/gateway-client-client.yaml
- secrets-yaml/gateway-service.yaml
- secrets-yaml/gateway-peering.yaml
- secrets-yaml/analytics-ingestion-client.yaml
- secrets-yaml/portal-admin-client.yaml
- secrets-yaml/wmapigateway-mgmt-client.yaml
- secrets-yaml/ingress-ca.yaml
- secrets-yaml/management-ca.yaml

# Patches para endpoints específicos
patches:
- path: patches/managementcluster-patch.yaml
  target:
    kind: ManagementCluster
    name: management
- path: patches/gatewaycluster-patch.yaml
  target:
    kind: GatewayCluster
    name: gateway
