
namespace: apic-lab

resources:
- gateway-peering.yaml
- gateway-service.yaml
- admin-secret.yaml

patches:
- path: patches/gatewaycluster-patch.yaml
  target:
    kind: GatewayCluster
    name: gateway