apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsCluster
metadata:
  name: analytics-apic-lab
  labels:
    app.kubernetes.io/instance: analytics
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: analytics-apic-lab
spec:
  license:
    accept: true
    license: L-PDZK-TWDH97
    metric: PROCESSOR_VALUE_UNIT
    use: nonproduction
  certManagerIssuer:
    kind: Issuer
    name: selfsigning-issuer
  imagePullSecrets:
    - ibm-entitlement-key
  devPortalMode: true
  ingestion:
    enabled: true
    geoIPEnabled: true
    pipelineBatchDelay: 10
    clientSubjectDN: 'CN=analytics-ingestion-client,O=cert-manager'
    clientAuthEnabled: true
    configReloadAutomatic: true
    queue:
      defaultQueueSize: 8Gi
      type: persisted
      volumeClaimTemplate:
        storageClassName: ocs-external-storagecluster-ceph-rbd
        volumeSize: 50Gi
    pipelineWorkers: 4
    endpoint:
      annotations:
        cert-manager.io/issuer: ingress-issuer
      hosts:
        - name: ai.apiclab.apps.itz-h4eig5.infra01-lb.lon04.techzone.ibm.com
          secretName: analytics-ai-endpoint
    pipelineBatchSize: 2000
  mgmtPlatformEndpointSvcCASecret:
    secretName: management-ca
  profile: n1xc2.m16
  analyticsMode: true
  external:
    offload:
      output: ''
    offload2:
      output: ''
  microServiceSecurity: certManager
  mgmtPlatformEndpointCASecret:
    secretName: ingress-ca
  version: 12.1.0.2
  imageRegistry: cp.icr.io/cp/apic
  storage:
    enabled: true
    shared:
      volumeClaimTemplate:
        storageClassName: ocs-external-storagecluster-ceph-rbd
        volumeSize: 200Gi
    type: shared
  federatedAPIManagementMode: true
