apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gwv6-apic-lab
spec:
  # Desabilita validação mTLS para permitir registro inicial do Gateway
  # mtlsValidateClient: false
  
  # Endpoints específicos do ambiente apic-lab
  gatewayEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: rgw.apiclab.apps.itz-h4eig5.infra01-lb.lon04.techzone.ibm.com
        secretName: gwv6-endpoint

  gatewayManagerEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: rgwd.apiclab.apps.itz-h4eig5.infra01-lb.lon04.techzone.ibm.com
        secretName: gwv6-manager-endpoint

# Made with Bob
