apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: gateway
  labels:
    app.kubernetes.io/instance: gateway
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: gateway
spec:
  version: 12.1.0.2
  profile: n1xc4.m8
  
  license:
    accept: true
    license: L-PDZK-TWDH97
    metric: PROCESSOR_VALUE_UNIT
    use: nonproduction
  
  imageRegistry: cp.icr.io/cp/apic
  imagePullSecrets:
    - ibm-entitlement-key
  
  peeringLogLevel: internal
  configSequenceInterval: 3000
  webGUIManagementPort: 9090
  webGUIManagementEnabled: false
  mtlsValidateClient: true
  apiDebugProbe: true
  apiDebugProbeMaxRecords: 1000
  apiDebugProbeExpirationMinutes: 60
  apicGatewayServiceV5CompatibilityMode: false
  defaultLogFormat: text
  datapowerLogLevel: 3
  
  updateStrategy:
    mode: automatic
  
  # Secrets - to be provided by overlay
  apicGatewayServiceTLS:
    secretName: gateway-service
  apicGatewayPeeringTLS:
    secretName: gateway-peering
  mgmtPlatformEndpointSvcCASecret:
    secretName: management-ca
  mgmtPlatformEndpointCASecret:
    secretName: ingress-ca
  adminUser:
    secretName: admin-secret
  
  # Storage - to be customized by overlay
  tokenManagementService:
    enabled: true
    storage:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      volumeSize: 30Gi
  
  # Endpoints - to be customized by overlay
  gatewayEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: gateway.example.com
        secretName: gateway-endpoint
  
  gatewayManagerEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: gateway-manager.example.com
        secretName: gateway-manager-endpoint

# Made with Bob
